title   NexusOS (Live)
linux   /vmlinuz-linux-zen
initrd  /intel-ucode.img
initrd  /amd-ucode.img
initrd  /initramfs-linux-zen.img
options splash quiet loglevel=3 rd.systemd.show_status=auto zswap.enabled=1 zswap.compressor=lz4

title   NexusOS (Persistent USB)
linux   /vmlinuz-linux-zen
initrd  /intel-ucode.img
initrd  /amd-ucode.img
initrd  /initramfs-linux-zen.img
options splash quiet loglevel=3 rd.systemd.show_status=auto cow_persistent=persistent_NexusOS.img

title   NexusOS (Safe Mode / 512MB RAM)
linux   /vmlinuz-linux-zen
initrd  /intel-ucode.img
initrd  /amd-ucode.img
initrd  /initramfs-linux-zen.img
options nomodeset mem=512M splash quiet loglevel=3
