title   NexusOS
linux   /vmlinuz-linux-zen
initrd  /intel-ucode.img
initrd  /amd-ucode.img
initrd  /initramfs-linux-zen.img
options nomodeset mem=512M cow_persistent=persistent_NexusOS.img splash quiet loglevel=3
